view_net_type: "default"
physical_rendering_network:
    darkroom: True
    gamma: 2.0
    ambient_network:
        d_feature: 256
        mode: idr
        d_in: 9
        d_out: 3
        d_hidden: 256
        n_layers: 4
        weight_norm: True
        multires_view: 4
        squeeze_out: True
    light_network:
        d_feature: 256
        mode: idr
        d_in: 10
        d_out: 3
        d_hidden: 256
        n_layers: 4
        weight_norm: True
        multires_view: 4
        multires_light: 4
        light_features: 1
        squeeze_out: True
brdf_settings:
    type: ambient_sep
    mask_shadowing: joint
    subsurface: 0
    dims: 0